### ISSUE TITLE
Move variables to separate file

### ISSUE THREAD

**Issue by danb35** [kjake/freenas-iocage-unifi#4]
You've made some updates to this script, and probably will again in the future.  To make it easier and less error-prone for your users, I'd suggest moving the variable declarations (JAIL_IP, JAIL_PATH, etc.) into a separate file--call it `freenas-iocage-unifi-config`, for example.  This file would be user-created (it wouldn't be part of your repo), and would be a permanent way for the user to set those options.  Your script would then `source freenas-iocage-unifi-config` to load in those variables.

The benefit of this would be that users could just pull the latest version of your script from git, drop it in the right place, and run it.  Updates are easier, and don't require manually editing anything.

**Comment by kjake** [comment]
I like it.  Would a common config file be to much trouble? For example, I suspect most would have all of their Jails under the same root path - so that variable wouldn't change for any jail script.  I'd have to change some variable names, like JAIL_IP should become CRASHPLAN_IP and UNIFI_IP. Or am I being too ambitious?

**Comment by danb35** [comment]
A common config file would require a little more structure--the crashplan script and the unifi script would have to be in some set relationship to each other, and you'd (as you recognize) need to deconflict the variables.  But neither of those sounds like a major issue.

Something that might complicate it a little, but would seem to naturally fit with this idea, would be for that config file to include a flag for Let's Encrypt (and possibly even the other variables like cloudflare key and email).  Your script would then only do the Let's Encrypt stuff if that flag was set.
